### ISSUE TITLE
Burger icon is sticky

### ISSUE THREAD

**Issue by wchrapcynski** [CotripperPlatform/CoTrip#397]
The burger icon sticks to the top right corner of the page and stays there when you scroll.

**Comment by andrew-frazier6** [comment]
@ZakkMan Took a break from Storybook Organization to work on this. Could you provide some context into where this burger would go and how many links I will need to create in the dropdown? I have scratched the old setup because of a bug that wasnt allowing it to show up so this will allow me to tailor the new Burger for exactly where and what we will need

**Comment by caioingber** [comment]
@andrew-frazier6 per our convo, this issue has been resolve in PR #403 , addressing additional issues in #285
